services:
  - type: web
    name: portfolio
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DJANGO_ENV
        value: prod
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "portfolio-xj33.onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio_db
          property: connectionString

databases:
  - name: portfolio_db
    databaseName: portfolio
    user: portfolio


